export enum AUTHORIZATION_EVENTS {
  ON_ACCEPTED = "Authorization@ACCEPTED",
  IS_ACCEPTED = "Authorization@IS_ACCEPTED",
  IS_NOT_ALLOWED = "Authorization@IS_NOT_ALLOWED"
}

export enum RESULTSET_EVENTS {
  CONTENT_FOUND = "RESULTSET@CONTENT_FOUND",
  CONTENT_NOT_FOUND = "RESULTSET@CONTENT_NOT_FOUND"
}

export enum GUARD_EVENTS {
  IS_ACCEPT = "GUARDS@ACCEPT",
  IS_DIE = "GUARDS@DIE",
  IS_ABORT = "GUARDS@ABORT",
  IS_CONTINUE = "GUARDS@CONTINUE"
}
export enum AUTH_EVENTS {
  ON_AUTH_ERROR = "AUTHENTICATOR@AUTH_ERROR"
}
